[[snippets]]
command = "curl -sL https://github.com/arkadiyt/bounty-targets-data/raw/master/data/bugcrowd_data.json | jq -r '.[].targets.in_scope[] | [.target, .type] | @tsv'"
description = "Get bugcrowd programs"
output = ""
tag = ["hackpet"]

