[[snippets]]
command = "curl -sL https://github.com/arkadiyt/bounty-targets-data/raw/master/data/intigriti_data.json | jq -r '.[].targets.in_scope[] | [.endpoint, .type] | @tsv'"
description = "Get intigriti programs"
output = ""
tag = ["hackpet"]

