[[snippets]]
command = "cat <domains file> | parallel -j50 -q curl -w 'Status:%{http_code}\\t  Size:%{size_download}\\t %{url_effective}\\n' -o /dev/null -sk"
description = "URLs Probing with cURL + Parallel"
output = ""
tag = ["hackpet"]

