# hackpet :: android_set_proxy.toml
[[snippets]]
command = "adb shell settings put global http_proxy <ip address>:<param>"
description = "Android set proxy"
output = ""
tag = ["hackpet"]

# hackpet :: android_unset_proxy.toml
[[snippets]]
command = "adb shell settings put global http_proxy :0"
description = "Android unset proxy"
output = ""
tag = ["hackpet"]

# hackpet :: bf_endpoint_dirsearch.toml
[[snippets]]
command = "dirsearch -e php,asp,aspx,jsp,py,txt,conf,config,bak,backup,swp,old,db,sql -u <URL>"
description = "Brute forcing for endpoints with dirsearch"
output = ""
tag = ["hackpet"]

# hackpet :: certprobe.toml
[[snippets]]
command = "curl -s https://crt.sh/\\?q\\=\\%.<domain>\\&output\\=json | jq -r '.[].name_value' | sed 's/\\*\\.//g' | sort -u | httprobe | tee -a ./all.txt"
description = "certprobe / runs httprobe on all the hosts from certspotter"
output = ""
tag = ["hackpet"]

# hackpet :: find_subdomain_takeover_1.toml
[[snippets]]
command = "subfinder -d <domain> >> domains ; assetfinder -subs-only <domain> >> domains ; amass enum -norecursive -noalts -d <domain> >> domains ; subjack -w domains -t 100 -timeout 30 -ssl -c ~/go/src/github.com/haccer/subjack/fingerprints.json -v  | tee takeover"
description = "Find subdomain and takeover (with subfinder/amass/assetfinder/subjack)"
output = ""
tag = ["hackpet"]

# hackpet :: get_url_param.toml
[[snippets]]
command = "echo <domain> | ~/go/bin/gau | grep \"=\" | qsreplace -a "
description = "Get url with gau, included parameter"
output = ""
tag = ["hackpet"]

# hackpet :: geturl_urlscanio.toml
[[snippets]]
command = "gron \"https://urlscan.io/api/v1/search/?q=domain:<domain>\"  | grep 'url' | gron --ungron"
description = "Get urls from urlscanio"
output = ""
tag = ["hackpet"]

# hackpet :: ipinfo.toml
[[snippets]]
command = "curl http://ipinfo.io/<param>"
description = "ipinfo"
output = ""
tag = ["hackpet"]

# hackpet :: make_wordlist_params.toml
[[snippets]]
command = "waybackurls <domain> |  grep \"?\" | unfurl keys  | sort -u | tee -a paramlist.txt"
description = "Create a wordlist using param used in the domain"
output = ""
tag = ["hackpet"]

